-- AlterTable: Add addon fields to cart_items and order_items

ALTER TABLE "cart_items"
ADD COLUMN IF NOT EXISTS "hasAddon" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "addons" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "metadata" JSONB;

ALTER TABLE "order_items"
ADD COLUMN IF NOT EXISTS "hasAddon" BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS "addons" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

