export default function TermsConditionsPage() {
    return (
        <div className="min-h-screen bg-white">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16 lg:py-20">
                {/* Header Section */}
                <div className="text-center mb-12 sm:mb-16">
                    {/* Terms & Conditions Badge */}
                    <div className="inline-flex items-center gap-2 px-4 py-2 bg-gray-100 rounded-full border border-gray-200 mb-6">
                        <svg className="w-4 h-4 text-gray-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                        </svg>
                        <span className="text-xs sm:text-sm font-medium text-gray-700">TERMS & CONDITIONS</span>
                    </div>

                    {/* Main Title */}
                    <h1 className="text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 mb-4 tracking-tight">
                        Terms & Conditions
                    </h1>
                </div>

                {/* Content Sections */}
                <div className="space-y-10 sm:space-y-12">
                    {/* Electronic Record */}
                    <section>
                        <div className="flex items-start gap-4 mb-4">
                            <div className="w-10 h-10 bg-[#008ECC]/10 rounded-xl flex items-center justify-center shrink-0">
                                <svg className="w-5 h-5 text-[#008ECC]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                                </svg>
                            </div>
                            <div className="flex-1">
                                <h2 className="text-2xl sm:text-3xl font-semibold text-gray-900 mb-4">Electronic Record</h2>
                                <div className="space-y-4 text-base sm:text-lg text-gray-600 leading-relaxed">
                                    <p>
                                        This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                                    </p>
                                    <p>
                                        This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the Platform, including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                                    </p>
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* Platform Owner */}
                    <section>
                        <div className="flex items-start gap-4 mb-4">
                            <div className="w-10 h-10 bg-[#008ECC]/10 rounded-xl flex items-center justify-center shrink-0">
                                <svg className="w-5 h-5 text-[#008ECC]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                                </svg>
                            </div>
                            <div className="flex-1">
                                <h2 className="text-2xl sm:text-3xl font-semibold text-gray-900 mb-4">Platform Owner</h2>
                                <p className="text-base sm:text-lg text-gray-600 leading-relaxed">
                                    The Platform is owned by PAGZ, a company incorporated under the Companies Act, 1956 with its registered office at SHOP NO- 16, AMBER CHOWK, SHOP NO-16, AMBER CHOWK, KACHHARI ROAD, KACHHARI ROAD, Nalanda College, AMBER CHOWK, Biharsharif AMBER, Bihar Sharif, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
                                </p>
                            </div>
                        </div>
                    </section>

                    {/* Terms of Use */}
                    <section>
                        <div className="flex items-start gap-4 mb-4">
                            <div className="w-10 h-10 bg-[#008ECC]/10 rounded-xl flex items-center justify-center shrink-0">
                                <svg className="w-5 h-5 text-[#008ECC]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                                </svg>
                            </div>
                            <div className="flex-1">
                                <h2 className="text-2xl sm:text-3xl font-semibold text-gray-900 mb-4">Terms of Use</h2>
                                <div className="space-y-4 text-base sm:text-lg text-gray-600 leading-relaxed">
                                    <p>
                                        Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
                                    </p>
                                    <p>
                                        These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
                                    </p>
                                    <p>
                                        For the purpose of these Terms of Use, wherever the context so requires 'you', 'your' or 'user' shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                                    </p>
                                    <p className="font-semibold text-gray-900">
                                        ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* Conditions of Use */}
                    <section>
                        <div className="flex items-start gap-4 mb-4">
                            <div className="w-10 h-10 bg-[#008ECC]/10 rounded-xl flex items-center justify-center shrink-0">
                                <svg className="w-5 h-5 text-[#008ECC]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
                                </svg>
                            </div>
                            <div className="flex-1">
                                <h2 className="text-2xl sm:text-3xl font-semibold text-gray-900 mb-4">Conditions of Use</h2>
                                <p className="text-base sm:text-lg text-gray-600 leading-relaxed mb-4">
                                    The use of Platform and/or availing of our Services is subject to the following Terms of Use:
                                </p>
                                <ul className="space-y-3 text-base sm:text-lg text-gray-600 leading-relaxed list-none">
                                    <li className="flex items-start gap-3">
                                        <span className="text-[#008ECC] mt-1 shrink-0">•</span>
                                        <span>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</span>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <span className="text-[#008ECC] mt-1 shrink-0">•</span>
                                        <span>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</span>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <span className="text-[#008ECC] mt-1 shrink-0">•</span>
                                        <span>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</span>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <span className="text-[#008ECC] mt-1 shrink-0">•</span>
                                        <span>The contents of the Platform and the Services are proprietary to us and are licensed to You. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</span>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <span className="text-[#008ECC] mt-1 shrink-0">•</span>
                                        <span>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</span>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <span className="text-[#008ECC] mt-1 shrink-0">•</span>
                                        <span>You agree to pay us the charges associated with availing the Services.</span>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <span className="text-[#008ECC] mt-1 shrink-0">•</span>
                                        <span>You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</span>
                                    </li>
                                    <li className="flex items-start gap-3">
                                        <span className="text-[#008ECC] mt-1 shrink-0">•</span>
                                        <span>You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </section>

                    {/* Transactions and Contracts */}
                    <section>
                        <div className="flex items-start gap-4 mb-4">
                            <div className="w-10 h-10 bg-[#008ECC]/10 rounded-xl flex items-center justify-center shrink-0">
                                <svg className="w-5 h-5 text-[#008ECC]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                                </svg>
                            </div>
                            <div className="flex-1">
                                <h2 className="text-2xl sm:text-3xl font-semibold text-gray-900 mb-4">Transactions and Contracts</h2>
                                <p className="text-base sm:text-lg text-gray-600 leading-relaxed">
                                    You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services.
                                </p>
                            </div>
                        </div>
                    </section>

                    {/* Indemnification */}
                    <section>
                        <div className="flex items-start gap-4 mb-4">
                            <div className="w-10 h-10 bg-[#008ECC]/10 rounded-xl flex items-center justify-center shrink-0">
                                <svg className="w-5 h-5 text-[#008ECC]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                                </svg>
                            </div>
                            <div className="flex-1">
                                <h2 className="text-2xl sm:text-3xl font-semibold text-gray-900 mb-4">Indemnification</h2>
                                <p className="text-base sm:text-lg text-gray-600 leading-relaxed">
                                    You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
                                </p>
                            </div>
                        </div>
                    </section>

                    {/* Force Majeure */}
                    <section>
                        <div className="flex items-start gap-4 mb-4">
                            <div className="w-10 h-10 bg-[#008ECC]/10 rounded-xl flex items-center justify-center shrink-0">
                                <svg className="w-5 h-5 text-[#008ECC]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                                </svg>
                            </div>
                            <div className="flex-1">
                                <h2 className="text-2xl sm:text-3xl font-semibold text-gray-900 mb-4">Force Majeure</h2>
                                <p className="text-base sm:text-lg text-gray-600 leading-relaxed">
                                    Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
                                </p>
                            </div>
                        </div>
                    </section>

                    {/* Governing Law */}
                    <section>
                        <div className="flex items-start gap-4 mb-4">
                            <div className="w-10 h-10 bg-[#008ECC]/10 rounded-xl flex items-center justify-center shrink-0">
                                <svg className="w-5 h-5 text-[#008ECC]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                                </svg>
                            </div>
                            <div className="flex-1">
                                <h2 className="text-2xl sm:text-3xl font-semibold text-gray-900 mb-4">Governing Law</h2>
                                <div className="space-y-4 text-base sm:text-lg text-gray-600 leading-relaxed">
                                    <p>
                                        These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
                                    </p>
                                    <p>
                                        All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in Bihar Sharif and Bihar.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* Contact Information */}
                    <section>
                        <div className="flex items-start gap-4 mb-4">
                            <div className="w-10 h-10 bg-[#008ECC]/10 rounded-xl flex items-center justify-center shrink-0">
                                <svg className="w-5 h-5 text-[#008ECC]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                                </svg>
                            </div>
                            <div className="flex-1">
                                <h2 className="text-2xl sm:text-3xl font-semibold text-gray-900 mb-4">Contact Information</h2>
                                <p className="text-base sm:text-lg text-gray-600 leading-relaxed">
                                    All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website.
                                </p>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    );
}

